source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SocaCryptoiOS', :exclusive => true do
  pod "SocaCrypto", :path => "../"
end

target 'SocaCryptoiOSTests', :exclusive => true do
    pod "SocaCrypto", :path => "../"
    
    pod 'Specta'
    pod 'Expecta'
end

target 'SocaCryptoOSX', :exclusive => true do
    platform :osx, '10.10'
    
    pod "SocaCrypto", :path => "../"
end

target 'SocaCryptoOSXTests', :exclusive => true do
    platform :osx, '10.10'
    
    pod "SocaCrypto", :path => "../"
    
    pod 'Specta'
    pod 'Expecta'
end